const typingWords=["appreciation","likes","cheers","kudos","hearts","feedback","love"];let wordIndex=0,charIndex=typingWords[wordIndex].length,isDeleting=!1,typingSpeed=100,hasStarted=!1;const prefersReducedMotion=window.matchMedia("(prefers-reduced-motion: reduce)").matches;function typeWriter(){var e,t=document.getElementById("typed-words");t&&(prefersReducedMotion?t.textContent="likes":(e=typingWords[wordIndex],hasStarted||(hasStarted=!0,isDeleting=!0,charIndex=e.length),isDeleting?(t.textContent=e.substring(0,charIndex-1),charIndex--,typingSpeed=50,0===charIndex&&(isDeleting=!1,wordIndex=(wordIndex+1)%typingWords.length,typingSpeed=500)):(t.textContent=e.substring(0,charIndex+1),charIndex++,typingSpeed=100,charIndex===e.length&&(isDeleting=!0,typingSpeed=2e3)),setTimeout(typeWriter,typingSpeed)))}function copyCode(t){var e=t.parentElement,o=t.closest(".setup-section, .customise-section"),o=o?o.querySelector(".icon-selector"):null;let n="";o?(o={"icon-heart":"heart-code","icon-thumbs":"thumbs-code","icon-upvote":"upvote-code","icon-emoji":"emoji-code"}[o.querySelector('input[name="icon-selector"]:checked')?.id])&&(o=e.querySelector(`.${o} code`))&&(n=o.textContent):(o=e.querySelector("code"))&&(n=o.textContent),navigator.clipboard.writeText(n).then(()=>{const e=t.textContent;t.textContent="copied!",t.style.background="var(--success)",setTimeout(()=>{t.textContent=e,t.style.background=""},2e3)}).catch(e=>{console.error("Failed to copy: ",e),t.textContent="failed",t.style.background="var(--warning)",setTimeout(()=>{t.textContent="copy",t.style.background=""},2e3)})}function initCopyButtons(){document.querySelectorAll(".copy-btn").forEach(e=>{e.addEventListener("click",()=>copyCode(e))})}function initSmoothScrolling(){document.querySelectorAll('a[href^="#"]').forEach(e=>{e.addEventListener("click",function(e){e.preventDefault();var e=this.getAttribute("href");if("#"===e)window.scrollTo({top:0,behavior:"smooth"});else{const t=document.querySelector(e);t&&(e=document.querySelector(".navbar").offsetHeight,e=t.offsetTop-e-20,window.scrollTo({top:e,behavior:"smooth"}),setTimeout(()=>{t.focus()},300))}})})}const coolEmoji=["🔥","💀","💯","🚀","🎉","♥️"];let emojiIndex=0;function rotateEmoji(){const t=document.getElementById("rotating-emoji");t&&(prefersReducedMotion?t.textContent=coolEmoji[0]:setTimeout(()=>{emojiIndex=(emojiIndex+1)%coolEmoji.length,t.textContent=coolEmoji[emojiIndex];var e=document.getElementById("icon-emoji");e&&e.checked&&updateCustomEmojiPreview()},150))}function updateCustomEmojiPreview(){var e=document.querySelector(".emoji-preview .icon"),t=document.querySelector(".emoji-code code"),o=coolEmoji[emojiIndex];e&&(e.textContent=o),t&&(t.textContent=`<button
  class="iine-button"
  data-icon="${o}"
  aria-hidden="true">
</button>`)}function initEmojiListener(){const e=document.getElementById("icon-emoji");e&&e.addEventListener("change",()=>{e.checked&&updateCustomEmojiPreview()})}const createCelebration=t=>{if(!prefersReducedMotion){var o=t.getBoundingClientRect(),i=o.left+o.width/2,r=o.top+o.height/2,o=t.dataset.icon;let e;"heart"===o?e="❤️":"thumbs_up"===o?e="👍":"upvote"===o&&(e="⬆️");for(let n=0;n<6;n++){const c=document.createElement("div");c.textContent=e,c.style.cssText=`
      position: fixed;
      left: ${i}px;
      top: ${r}px;
      font-size: 24px;
      pointer-events: none;
      z-index: 9999;
      transition: all 1s ease-out;
      user-select: none;
    `,document.body.appendChild(c),c.offsetHeight,requestAnimationFrame(()=>{var e=n/6*Math.PI*2,t=80+50*Math.random(),o=Math.cos(e)*t,e=Math.sin(e)*t;c.style.transform=`translate(${o}px, ${e}px)`,c.style.opacity="0"}),setTimeout(()=>{document.body.contains(c)&&document.body.removeChild(c)},1100)}}};document.addEventListener("DOMContentLoaded",()=>{prefersReducedMotion?(typeWriter(),rotateEmoji()):(setTimeout(typeWriter,1800),setInterval(rotateEmoji,3e3)),initCopyButtons(),initSmoothScrolling(),initEmojiListener(),document.querySelectorAll(".hero-btn").forEach(e=>{const t=()=>{"true"!==e.getAttribute("aria-disabled")&&createCelebration(e)};e.addEventListener("click",t),e.addEventListener("keydown",e=>{"Enter"!==e.key&&" "!==e.key||t()})})});